Set URI values in homepage and repository
Pip/poetry fail to install this otherwise, as they require homepage and
repository to be valid URIs:

      RuntimeError: The Poetry configuration is invalid:
        - data.repository must be uri

and
      RuntimeError: The Poetry configuration is invalid:
        - data.homepage must be uri